version: '3.8'

services:
  menu-service:
    build: ./menu-service
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/menu
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "3002:3000"
    environment:
      - MENU_SERVICE_URL=http://menu-service:3000
      - INVENTORY_SERVICE_URL=http://inventory-service:3000
      - CUSTOMER_SERVICE_URL=http://customer-service:3000
    depends_on:
      - menu-service
      - inventory-service
      - customer-service

  inventory-service:
    build: ./inventory-service
    ports:
      - "3003:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/inventory
    depends_on:
      - mongodb

  customer-service:
    build: ./customer-service
    ports:
      - "3004:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/customers
    depends_on:
      - mongodb

  payment-service:
    build: ./payment-service
    ports:
      - "3005:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payments
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 