name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: ['menu-service', 'order-service', 'inventory-service', 'customer-service', 'payment-service']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.service }}
        npm install
    
    - name: Run tests
      run: |
        cd ${{ matrix.service }}
        npm test
    
    - name: Build Docker image
      run: |
        cd ${{ matrix.service }}
        docker build -t ${{ matrix.service }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Push Docker image
      run: |
        cd ${{ matrix.service }}
        docker tag ${{ matrix.service }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        docker-compose down
        docker-compose pull
        docker-compose up -d 